# Generated by Django 3.1 on 2020-08-11 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200810_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='details_url',
        ),
        migrations.AddField(
            model_name='location',
            name='place_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Подробная информация о локации'),
            preserve_default=False,
        ),
    ]
