# Generated by Django 3.1 on 2020-08-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200810_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='details_url',
        ),
    ]
