# Generated by Django 3.1 on 2020-08-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20200817_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Уникальный идентификатор локации'),
        ),
        migrations.AddField(
            model_name='place',
            name='short_title',
            field=models.CharField(max_length=30, null=True, verbose_name='Короткий заголовок для отображения на карте'),
        ),
    ]
