# Generated by Django 3.1 on 2020-08-17 17:45

from django.db import migrations


def move_location_datas_to_places(apps, schema_editor):
    Location = apps.get_model('places', 'Location')
    for location in Location.objects.all():
        location.place_info.short_title = location.title
        location.place_info.place_id = location.place_id
        location.place_info.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20200817_2040'),
    ]

    operations = [
        migrations.RunPython(move_location_datas_to_places),
    ]
