# Generated by Django 3.1 on 2020-08-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20200817_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
