# Generated by Django 3.1 on 2020-08-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(blank=True, max_length=400, verbose_name='Короткое описание'),
        ),
    ]
