# Generated by Django 3.1 on 2020-09-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20200817_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Уникальный идентификатор локации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='short_title',
            field=models.CharField(default='', max_length=30, verbose_name='Короткий заголовок для отображения на карте'),
            preserve_default=False,
        ),
    ]
